name: "Publish Release"

on:
  push:
    tags:
      - "v*" # Triggers only when you push a tag starting with 'v' (e.g., v1.0.0)

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "x86_64-apple-darwin"
          - platform: "macos-latest"
            target: "aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn" # This speeds up builds significantly

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav

      - name: install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GSTREAMER_PLUGINS: "core;playback;audio;video;alsa;pbtypes;libav;pulseaudio;good;ugly;bad"
        with:
          tagName: v__VERSION__ # the action replaces __VERSION__ from tauri.conf.json
          releaseName: "Creative v__VERSION__"
          releaseBody: "See the assets below to download."
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }}
